[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
subastas_program = "9qTFEzwXLX2mX4gz1t9A231iV5JmD1sjatatYbAnhVJj"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
