#!/bin/bash

# 🚀 Quick Start - Proyecto Escrow DApp
# Este script proporciona instrucciones para iniciar rápidamente

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                 Escrow DApp - Quick Start Guide               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Verificar si estamos en la carpeta correcta
if [ ! -d "sc" ] || [ ! -d "web" ]; then
    echo "❌ Error: Ejecuta este script desde la carpeta 'escrow/'"
    exit 1
fi

echo "✅ Estructura del proyecto verificada"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                        1️⃣  REQUISITOS                         ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Verifica que tengas instalado:"
echo "  ✓ Node.js v18+ : $(node --version 2>/dev/null || echo '❌ NO INSTALADO')"
echo "  ✓ Foundry      : $(forge --version 2>/dev/null | head -1 || echo '❌ NO INSTALADO')"
echo "  ✓ Git          : $(git --version 2>/dev/null | cut -d' ' -f3 || echo '❌ NO INSTALADO')"
echo ""

# Ofrecer instalar foundry si no está
if ! command -v forge &> /dev/null; then
    echo "⚠️  Foundry no detectado. Instálalo:"
    echo "   curl -L https://foundry.paradigm.xyz | bash"
    echo ""
fi

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║              2️⃣  INSTALAR DEPENDENCIAS                        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Opción A: Script automático (recomendado)"
echo "  $ ./setup.sh"
echo ""
echo "Opción B: Manual"
echo "  $ cd web && npm install && cd .."
echo "  $ cd sc && forge build && cd .."
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║              3️⃣  INICIAR BLOCKCHAIN LOCAL                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Abre una NUEVA TERMINAL y ejecuta:"
echo ""
echo "  $ anvil"
echo ""
echo "Verás algo como:"
echo "  Listening on 127.0.0.1:8545"
echo "  Account #0: 0x1234... (10000 ETH)"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║              4️⃣  COMPILAR SMART CONTRACTS                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "En otra NUEVA TERMINAL, ejecuta:"
echo ""
echo "  $ cd escrow/sc"
echo "  $ forge build"
echo "  $ forge test"
echo ""
echo "Si todo va bien, verás ✓ tests passed"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║              5️⃣  DESPLEGAR CONTRATOS                          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Desde la misma terminal (sc está abierto):"
echo ""
echo "  $ forge script script/Deploy.s.sol --rpc-url http://127.0.0.1:8545 --broadcast"
echo ""
echo "⚠️  IMPORTANTE: Anota la dirección de ESCROW_ADDRESS"
echo "   Ejemplo:"
echo "   Escrow deployed at: 0x1234567890abcdef..."
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║              6️⃣  CONFIGURAR FRONTEND                          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "En otra NUEVA TERMINAL, ejecuta:"
echo ""
echo "  $ cd escrow/web"
echo "  $ cp .env.example .env.local"
echo ""
echo "Abre .env.local y actualiza:"
echo ""
echo "  NEXT_PUBLIC_ESCROW_ADDRESS=0x1234567890abcdef..."
echo "  (La dirección del paso anterior)"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║              7️⃣  INICIAR FRONTEND                             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Desde la carpeta 'web':"
echo ""
echo "  $ npm run dev"
echo ""
echo "Abre en tu navegador: http://localhost:3000"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║              8️⃣  CONFIGURAR METAMASK                          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "1. Abre MetaMask"
echo "2. Agrega una red personalizada:"
echo "   - Network Name: Anvil Local"
echo "   - RPC URL: http://127.0.0.1:8545"
echo "   - Chain ID: 31337"
echo "   - Currency Symbol: ETH"
echo ""
echo "3. Importa una cuenta de anvil:"
echo "   - Copia la clave privada de anvil (terminal 1)"
echo "   - En MetaMask: Settings → Import Account"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║              ✅ ¡LISTO!                                        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Puedes ahora:"
echo ""
echo "  1️⃣  Conectar tu wallet (ConnectionButton)"
echo "  2️⃣  Agregar tokens permitidos (AddToken)"
echo "  3️⃣  Crear operaciones de intercambio (CreateOperation)"
echo "  4️⃣  Ver operaciones activas (OperationsList)"
echo "  5️⃣  Debug de balances (BalanceDebug)"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                  📚 DOCUMENTACIÓN                              ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Consulta estos archivos para más información:"
echo ""
echo "  📄 README.md                   - Visión general"
echo "  📄 START_HERE.md               - Guía paso a paso"
echo "  📄 ARCHITECTURE_SUMMARY.md     - Arquitectura técnica"
echo "  📄 VERIFICATION_CHECKLIST.md   - Lista de verificación"
echo "  📄 PROJECT_GENERATION_REPORT.md - Reporte de generación"
echo "  📄 DEPLOYMENT.md               - Desplegar a producción"
echo "  📄 TESTING.md                  - Ejecutar tests"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                  🆘 TROUBLESHOOTING                            ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "❓ \"Contract not deployed\""
echo "   ✓ Verifica NEXT_PUBLIC_ESCROW_ADDRESS en .env.local"
echo "   ✓ Asegúrate que anvil sigue corriendo"
echo ""
echo "❓ \"Cannot read properties of undefined\""
echo "   ✓ MetaMask no conectada o no se autorizó la página"
echo "   ✓ Actualiza el navegador (F5)"
echo ""
echo "❓ \"Insufficient balance\""
echo "   ✓ Usa direcciones de anvil (tienen 10000 ETH)"
echo "   ✓ Importa de nuevo la clave privada"
echo ""
echo "❓ \"Network mismatch\""
echo "   ✓ Verifica que MetaMask esté en Anvil Local (Chain ID 31337)"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "Para empezar: sigue los 8 pasos arriba en orden"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
